def get_reverse_complement(seq):
    """获取序列的反向互补序列"""
    complement_dict = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
    return "".join(complement_dict.get(base, base) for base in reversed(seq.upper()))


def calculate_identity(seq1, seq2):
    """计算两条序列的匹配度百分比"""
    if not seq1 or not seq2:
        return 0, 0, 0

    len1, len2 = len(seq1), len(seq2)
    if len1 != len2:
        print(f"⚠️ 警告：两条序列长度不一致 (蚊体: {len1}bp, C6/36: {len2}bp)！")
        print("这可能导致比对错位，建议检查复制的序列是否完整。")

    min_len = min(len1, len2)
    matches = sum(1 for i in range(min_len) if seq1[i] == seq2[i])
    identity_pct = (matches / min_len) * 100
    return matches, min_len, identity_pct


def check_primers_and_identity(seq_mosquito, seq_c636, f_primer, r_primer):
    """综合检查序列匹配度及引物有效性"""

    f_primer = f_primer.upper()
    r_primer = r_primer.upper()
    rc_r_primer = get_reverse_complement(r_primer)

    print("=" * 55)
    print("【序列比对与引物诊断综合报告】")
    print("=" * 55)

    # --- 1. 计算整体序列匹配度 ---
    matches, total_len, identity = calculate_identity(seq_mosquito, seq_c636)
    if total_len > 0:
        print("📊 全长序列比对结果：")
        print(f"  ▶ 序列长度: {total_len} bp")
        print(f"  ▶ 完全匹配碱基数: {matches}")
        print(f"  ▶ 匹配度 (Identity): {identity:.2f}%")
        print("-" * 55)
    else:
        print("⚠️ 提示：尚未输入全长序列数据，无法计算匹配度。")
        print("-" * 55)

    # --- 2. 检查正向引物 ---
    f_in_mosq = f_primer in seq_mosquito
    f_in_c636 = f_primer in seq_c636

    print(f"🔬 正向引物 (F): {f_primer}")
    if f_in_mosq and f_in_c636:
        print("  ✅ 完美！在两种细胞中均 100% 匹配。")
    elif f_in_mosq:
        print("  ❌ 警告：仅在【蚊体】中匹配，在 C6/36 中有错配！")
    elif f_in_c636:
        print("  ❌ 警告：仅在【C6/36】中匹配，在蚊体中有错配！")
    else:
        print("  ⚠️ 提示：在两段序列中都没找到正向引物。")

    print("-" * 55)

    # --- 3. 检查反向引物 ---
    rc_in_mosq = rc_r_primer in seq_mosquito
    rc_in_c636 = rc_r_primer in seq_c636

    print(f"🔬 反向引物 (R): {r_primer}")
    print(f"   (搜索用反向互补序列: {rc_r_primer})")

    if rc_in_mosq and rc_in_c636:
        print("  ✅ 完美！在两种细胞中均 100% 匹配。")
    elif rc_in_mosq:
        print("  ❌ 警告：仅在【蚊体】中匹配，在 C6/36 中有错配！")
    elif rc_in_c636:
        print("  ❌ 警告：仅在【C6/36】中匹配，在蚊体中有错配！")
    else:
        print("  ⚠️ 提示：在两段序列中都没找到反向引物。")

    print("=" * 55)

    # --- 4. 最终结论 ---
    if f_in_mosq and f_in_c636 and rc_in_mosq and rc_in_c636:
        print("🎉 最终结论：引物成功避开所有错配点，【可以】通用扩增！")
    else:
        print("⚠️ 最终结论：引物结合区域存在错配，【不建议】通用，需重新设计。")
    print("=" * 55)


# ==========================================
# ⬇️ 请在下方三个引号 """ 之间粘贴你的完整序列 ⬇️
# ==========================================

raw_seq_mosquito = "ATGAGACTTCTTTCGCCGCACTGTCTGATAGCGGTCACTTTTGCCGCTATCTTGACGGCAACTGCGTTCGCCGCACAAGACAAGAAGGAACAAGACTACGGTACCGTTATCGGCATTGACCTGGGAACGACCTACTCATGCGTAGGCGTCTACAAGAACGGACGCGTGGAAATCATTGCAAACGATCAGGGCAATCGTATCACGCCGTCCTATGTGGCGTTCACTTCCGATGGTGAACGATTGATTGGCGATGCTGCCAAGAATCAACTTACCACCAATCCAGAGAACACTATCTTCGACGCCAAGCGTCTGATTGGACGCGAGTTCAATGATCCAACTGTGCAGCAGGACATGAAACTGTTTCCGTTCAAGGTCATGGAGAAGAACTCCAAGCCGAATGTAAAAGTAAGCACCAATCAAGGTGAAAAGACTTTCTCGCCAGAGGAGATCTCCGCAATGGTTCTGGGAAAGATGAAGGAAACCGCGGAAGAGTATCTCGGCAAAAAGGTGACCCACGCGGTAGTTACCGTTCCGGCGTACTTCAACGATGCTCAACGCCAAGCTACCAAGGATGCAGGGACCATTGCCGGATTGATCGTTATGCGTATCATTAACGAACCCACGGCTGCTGCTATCGCTTACGGCTTGGACAAAAAGGAAGGCGAGAAGAACATCCTGGTGTTTGACTTAGGCGGTGGTACTTTCGATGTATCCCTGTTGACCATCGACAACGGAGTTTTCGAAGTGGTTGCTACCAACGGGGACACCCATTTGGGTGGCGAAGACTTTGACCAGCGTGTGATGGATCATTTCATCAGAGTTTACATGAAGAAGCATGGAAAGGACATCCGACAGGATGTTCGCGCTGTTCAGAAGCTACGCAGAGAGGTGGAGAAGGCGAAGCGTGCGCTATCATCCAGCCACCAGGTTCGCATTGAGATTGAGTCGTTCTTTGAAGGTGAAGACTTTAGCGAAACTTTAACCCGGGCCAAATTCGAAGAGTTGAACATGGATTTGTTTAGAGCCACCATGAAACCGGTGCAGAAAGTTCTTGAGGATGCCGACATGAACAAGAAGGATGTTGACGAGATTGTTCTGGTTGGAGGTCAGCAGCTGGTCAAGGAATTCTTCAACGGCAAGGAGCCATCGCGCGGGATTAATCCTGACGAAGCTGTAGCATATGGAGCTGCCGTTCAAGCTGGGGTGCTTTCGGGCGCTACCGAAACCGAAGGGCTTTTACTTCTGGACGTGAATCCGCTAACATTAGGCATTGAAACTGTCGGCGGAGTCATGACCAAGTTGATTCCTCGTAATAGCGTCATTCCAACGAAGAAGTCTCAGATCTTCTCAACAGCCTCTGATAACCAACATACCGTAACAATCCAGATCTTCGAAGGTGAGCGTCCTCTGACCAAGGATAACCATCTGCTCGGCAAGTTCGACCTTACAGGAATCCCACCGGCACCACGAGGAATGCCACAGATCGAAGTATCGTTTGAAATCGACGCGAACGGCATTCTGCAGGTATCCGCTGAAGATAAGGGGACTGGTAATCGCGAGAAGATTGTCATTACCAACGACCAAAACCGTCTGACTCCGGACGATATCGAACGCATGATTCAGGATGCGGAGAGATTCGCCGAAGATGACAAGAAACTAAAAGAACGGGTAGATGCCCTTCATGAGCTGGAGAGCTATGCGTATAATCTGAAAAATCAAATCAACGATAAGGAGAAACTGGGATCGAAACTTTCCGACGATGAGAAGAGCAAGATTGAGGAGGCGGTCGATGAGAAGATCAAGTGGCTGGACGCGAATCAGAATGCGGACACGGAGGAACTTAGGAGTCAGCGCAAGGAACTCGAAGAAGTCGCTCAGCCGATCATCGCCAAGTTGTACGCCAGTGGTGAAAGTTCACCGCAGCCGGACACTGAAAGCGAAGATGATGAGGATCCATTCAATGATGAATTGTAG"


raw_seq_c636 = "ATGAGACTTCTTTCGCCGCAATGTCTGATAGCGGTCACTTTTGCCGCTATCTTGACGGCAACTGCGTTCGCCGCACAAGACAAGAAGGAACAAGACTACGGTACCGTTATCGGCATTGACCTGGGAACGACCTACTCATGCGTAGGCGTCTACAAGAACGGACGCGTGGAAATCATTGCAAACGATCAGGGCAATCGTATCACGCCGTCCTATGTGGCGTTCACTTCCGATGGTGAACGATTGATTGGCGATGCGGCCAAGAATCAACTCACCACCAACCCAGAGAACACTATCTTCGACGCCAAGCGTCTGATTGGTCGGGAGTTCAATGATCCAACTGTGCAGCAGGACATGAAACTGTTTCCGTTCAAGGTCACGGAGAAGAACTCCAAACCAAACGTAAAGGTCAGCACCAATCAAGGTGAGAAGACCTTCACGCCAGAAGAGATCTCCGCAATGGTTCTGGGAAAGATGAAGGAAACCGCGGAAGAGTACCTCGGCAAAAAGGTAACCCACGCGGTAGTTACCGTTCCGGCGTACTTCAACGATGCTCAACGTCAAGCTACCAAGGATGCAGGAACCATTGCCGGATTGAACGTTATGCGTATCATTAACGAACCCACGGCTGCCGCTATAGCTTACGGCTTGGACAAAAAGGAAGGCGAGAAGAACATCCTGGTGTTTGACCTTGGTGGTGGTACCTTCGATGTATCCCTGTTGACCATTGACAACGGAGTTTTCGAAGTGGTTGCTACCAACGGGGATACCCATTTGGGAGGCGAAGACTTTGACCAGCGAGTGATGGATCATTTCATCAGAGTTTACATGAAGAAGCATGGAAAGGACATCCGACAGGATGTTCGCGCTGTTCAGAAGCTACGCAGAGAGGTGGAGAAGGCCAAGCGTGCGCTATCATCCAGCCATCAGGTTCGCATTGAGATTGAGTCGTTCTTCGAAGGTGAAGACTTTAGCGAAACTTTAACCCGAGCCAAGTTCGAAGAGTTGAACATGGATTTGTTTAGAGCCACCATGAAACCGGTGCAGAAAGTTCTTGAGGATGCCGACATGAACAAGAAGGATGTTGACGAGATTGTTCTGGTTGGAGGATCCACGCGTATCCCTAAGGTTCAGCAGCTGGTCAAGGAATTCTTCAACGGCAAGGAGCCATCGCGTGGGATCAATCCAGACGAAGCAGTGGCATATGGAGCAGCCGTTCAAGCTGGGGTGCTTTCGGGTGCTACCGAAACCGAAGGACTTTTACTACTGGACGTGAATCCGCTGACTTTAGGCATTGAAACTGTTGGCGGTGTTATGACCAAGTTGATTCCTCGTAACAGCGTCATTCCAACGAAGAAGTCTCAGATCTTCTCAACAGCCTCTGATAACCAACATACCGTAACAATTCAGATCTTCGAAGGCGAGCGTCCTCTGACCAAGGATAACCATCTGCTCGGCAAGTTCGACCTTACAGGAATCCCACCGGCACCACGAGGAATGCCACAGATCGAAGTATCGTTTGAAATCGACGCTAACGGCATTCTGCAGGTATCCGCTGAAGATAAGGGGACTGGTAATCGCGAGAAGATTGTCATTACCAACGACCAAAACCGTCTGACTCCGGACGATATCGAACGCATGATTCAGGATGCGGAGAGATTCGCCGAAGATGACAAGAAACTAAAAGAACGGGTAGATGCCCTTCATGAGCTGGAGAGCTATGCGTATAATCTGAAAAATCAAATCAACGATAAGGAGAAACTGGGATCGAAACTTTCCGACGATGAGAAGAACAAAATTGAGGAGGCGATCGAAGAGAAGATCAAGTGGCTGGACGCGAATCAGAATGCGGACACGGAGGAACTTAGGAGTCATCGCAAGGAACTCGAAGAAGTCGCTCAGCCGATCATCGCCAAGTTGTACGCCAGTGGTGAAAGTTCACCGCAGCCGGACACTGAAGGAGAGGATGATGAAAATCCATTCAATGATGAATTGTAG"



# ==========================================
# ⬆️ 序列粘贴区结束 ⬆️
# ==========================================

# 你的引物序列
forward_primer = "CGTATCACGCCGTCCTATGT"
reverse_primer = "TTCACCTTGATTGGTGCTTACT "

# 自动清理序列
seq_mosquito_full = raw_seq_mosquito.replace("\n", "").replace(" ", "").replace("\r", "")
seq_c636_full = raw_seq_c636.replace("\n", "").replace(" ", "").replace("\r", "")

# 运行检查程序
check_primers_and_identity(seq_mosquito_full, seq_c636_full, forward_primer, reverse_primer)

